env: dev

development:
  gcp:
    project_id: e-commerce-user-behavior-dev
    location: us-central1

  cloud_storage:
    bucket: bucket-o26f5msw
    paths:
      raw: raw/
      bronze: bronze/
      silver: silver/
      gold: gold/

production:
  gcp:
    project_id: e-commerce-user-behavior-prod
    location: us-central1
