data:
  ingestion:
    origin: "dhrubangtalukdar/e-commerce-shopper-behavior-amazonshopify-based"
    destination: "data/raw/data.csv"
  bronze:
    origin: "data/raw/data.csv"
    destination: "data/bronze/data.csv"
  silver:
    origin: "data/bronze/data.csv"
    destination: "data/silver/data.csv"
  gold:
    origin: "data/silver/data.csv"
    destination: "data/gold/data.csv"
